Repository gridsuite/gridactions-app, pull requests merged in 2021-01, with the labels that each got.

#20 Make contingency list collapsible
  src/components/contingency-list.js
Labels: S

#17 move config to back
  .env
  package-lock.json
  package.json
  src/components/app.js
  src/components/parameters.js
  src/redux/reducer.js
  src/setupProxy.js
  src/utils/config-params.js
  src/utils/rest-api.js
Labels: functionally tested

#26 Add snackbar and manage error messages
  src/components/app.js
  src/components/contingency-list.js
  src/translations/en.json
  src/translations/fr.json
Labels: M

#28 Show error in textfield
  src/components/popup.js
  src/translations/en.json
  src/translations/fr.json
Labels: S
